version: '3.9'
services:
  postgres:
    image: postgres:12.0 # Aurora Postgres is v12
    container_name: trailertrader_postgres
    environment:
      DB_HOST: trailertrader-postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: trailertrader
      DB_CONNECTION: pgsql
    ports:
        - '5432:5432'
  php:
    build: ./
    container_name: trailertrader_php
    volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
    ports:
        - '8000:8000'
