version: '3.9'
services:
  postgres:
    image: postgres:12.0 # Aurora Postgres is v12
    container_name: trailertrader_postgres
    volumes:
        - ./bin/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASE}_test # just in case it was necessary, we could separate by comma, e.g: ${DB_DATABASE}_test1,${DB_DATABASE}_test2
    ports:
        - '5432:5432'
  php:
    build: ./
    container_name: trailertrader_php
    volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
    links:
        - postgres
    depends_on:
        - postgres
    ports:
        - '8000:8000'
