<?php

namespace App\Http\Requests\CRM\User;

use App\Http\Requests\Request;
use Illuminate\Validation\Rule;

class UpdateSettingsRequest extends Request {

    protected $rules = [
        'user_id' => 'required|integer',

        'price_per_mile' => 'numeric|required_without_all:email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'email_signature' => 'string|required_without_all:price_per_mile,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'timezone' => 'string|valid_timezone|required_without_all:price_per_mile,email_signature,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'enable_hot_potato' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'disable_daily_digest' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'enable_assign_notification' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'enable_due_notification' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'enable_past_notification' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',

        'default/filters/sort' => 'integer|valid_sort_orders_crm|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/delay' => 'integer|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/duration' => 'integer|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/end-hour' => 'string|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/skip-weekends' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/start-hour,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/start-hour' => 'string|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/use-submission-date',
        'round-robin/hot-potato/use-submission-date' => 'boolean|required_without_all:price_per_mile,email_signature,timezone,enable_hot_potato,disable_daily_digest,enable_assign_notification,enable_due_notification,enable_past_notification,default/filters/sort,round-robin/hot-potato/delay,round-robin/hot-potato/duration,round-robin/hot-potato/end-hour,round-robin/hot-potato/skip-weekends,round-robin/hot-potato/start-hour'
    ];
}
