<?php

namespace Tests\Unit\App\Services\WebsiteUser;

use App\Models\WebsiteUser\WebsiteUser;
use App\Repositories\WebsiteUser\WebsiteUserRepositoryInterface;
use App\Services\WebsiteUser\AuthService;
use Illuminate\Auth\Events\Registered;
use Illuminate\Support\Facades\Event;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\Common\TestCase;

class AuthServiceTest extends TestCase
{
    private MockObject $websiteUserRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function getConcreteService(): AuthService {
        $this->websiteUserRepository = $this->mockWebsiteUserRepository();
        return new AuthService($this->websiteUserRepository);
    }

    private function mockWebsiteUserRepository(): MockObject {
        return $this->createMock(WebsiteUserRepositoryInterface::class);
    }

    public function testRegister() {
        Event::fake();
        $attributes = [
            "first_name" => "Ryo",
            "last_name" => "Ryu",
            "address" => "",
            "zipcode" => "",
            "city" => "",
            "state" => "",
            "email" => "songxunzhao1992@gmail.com",
            "phone_number" => "",
            "mobile_number" => "",
            "password" => "12345678"
        ];
        $service = $this->getConcreteService();
        $this->websiteUserRepository->expects($this->once())
            ->method('create')
            ->will($this->returnValue(new WebsiteUser()));
        $service->register($attributes);
        Event::assertDispatched(Registered::class);
    }

    public function testAuthenticate() {

    }
}
