<?php

namespace Tests\Unit\App\Services\WebsiteUser;

use App\Services\WebsiteUser\AuthService;
use Tests\Common\TestCase;

class AuthServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function getConcreteService(): AuthService {

    }

    public function testRegister() {

    }

    public function testAuthenticate() {

    }
}
