<?php

declare(strict_types=1);

namespace App\Http\Requests\Inventory;

use App\Http\Requests\CreateRequestInterface;
use App\Http\Requests\Request;

class CreateInventoryRequest extends Request implements CreateRequestInterface
{
    protected array $rules = [
      'entity_type_id' => 'required_without_all:entity_type|integer',
      'dealer_id' => 'integer',
      'dealer_location_id' => 'required_without_all:dealer_location_identifier|integer',
      'active' => 'boolean|nullable',
      'title' => 'required|max:255',
      'stock' => 'string|max:50',
      'manufacturer' => 'inventory_mfg_name_valid|nullable',
      'brand' => 'inventory_brand_valid|nullable',
      'model' => 'string|max:255|nullable',
      'qb_item_category_id' => 'integer|nullable',
      'description' => 'string|nullable',
      'description_html' => 'string|nullable',
      'status' => 'integer|nullable',
      'status_id' => 'integer|nullable',
      'availability' => 'string|nullable',
      'is_consignment' => 'boolean|nullable',
      'category' => 'inventory_cat_valid',
      'video_embed_code' => 'nullable',
      'vin' => 'string|max:17|nullable',
      'geolocation' => 'string',
      'msrp_min' => 'numeric|nullable',
      'msrp' => 'numeric|nullable',
      'price' => 'numeric|nullable',
      'sales_price' => 'numeric|nullable',
      'use_website_price' => 'boolean|nullable',
      'website_price' => 'numeric|nullable',
      'dealer_price' => 'numeric|nullable',
      'monthly_payment' => 'numeric|nullable',
      'year' => 'integer',
      'chassis_year' => 'integer|nullable',
      'condition' => 'in:new,used,remfg|nullable',
      'length' => 'numeric|nullable',
      'width' => 'numeric|nullable',
      'height' => 'numeric|nullable',
      'weight' => 'numeric|nullable',
      'gvwr' => 'numeric|nullable',
      'axle_capacity' => 'numeric|nullable',
      'cost_of_unit' => 'numeric|nullable',
      'true_cost' => 'numeric|nullable',
      'cost_of_shipping' => 'string|max:255|nullable',
      'cost_of_prep' => 'string|max:255|nullable',
      'total_of_cost' => 'string|max:255|nullable',
      'pac_amount' => 'numeric|nullable',
      'pac_type' => 'in:percent,amount|nullable',
      'minimum_selling_price' => 'string|max:255|nullable',
      'notes' => 'string|nullable',
      'show_on_ksl' => 'boolean|nullable',
      'show_on_racingjunk' => 'boolean|nullable',
      'show_on_website' => 'boolean|nullable',
      'overlay_enabled' => 'in:0,1,2|nullable',
      'is_special' => 'boolean|nullable',
      'is_featured' => 'boolean|nullable',
      'latitude' => 'numeric|nullable',
      'longitude' => 'numeric|nullable',
      'is_archived' => 'boolean|nullable',
      'archived_at' => 'string|nullable',
      'broken_video_embed_code' => 'boolean|nullable',
      'showroom_id' => 'integer|nullable',
      'coordinates_updated' => 'integer|nullable',
      'payload_capacity' => 'numeric|nullable',
      'height_display_mode' => 'in:inches,feet|nullable',
      'width_display_mode' => 'in:inches,feet|nullable',
      'length_display_mode' => 'in:inches,feet|nullable',
      'width_inches' => 'numeric|nullable',
      'height_inches' => 'numeric|nullable',
      'length_inches' => 'numeric|nullable',
      'integration_item_hash' => 'string|max:32|nullable',
      'integration_images_hash' => 'string|max:32|nullable',
      'non_serialized' => 'boolean|nullable',
      'hidden_price' => 'numeric|nullable',
      'utc_integration_updated_at' => 'date',
      'has_stock_images' => 'boolean|nullable',

      'dealer_identifier' => 'integer',
      'entity_type' => 'required_without_all:entity_type_id|integer',
      'dealer_location_identifier' => 'required_without_all:dealer_location_id|integer',

      'length_second' => 'numeric|nullable',
      'length_inches_second' => 'numeric|nullable',
      'width_second' => 'numeric|nullable',
      'width_second_inches' => 'numeric|nullable',
      'height_second' => 'numeric|nullable',
      'height_second_inches' => 'numeric|nullable',

      'new_images' => 'array|nullable',
      'new_images.*.url' => 'string|required',
      'new_images.*.position' => 'integer|nullable',
      'new_images.*.primary' => 'checkbox|nullable',
      'new_images.*.is_default' => 'checkbox|nullable',
      'new_images.*.secondary' => 'checkbox|nullable',
      'new_images.*.is_secondary' => 'checkbox|nullable',
      'new_images.*.was_manually_added' => 'checkbox|nullable',

      'new_files' => 'array|nullable',
      'new_files.*.title' => 'string|nullable',
      'new_files.*.url' => 'string|required',
      'new_files.*.position' => 'integer|nullable',
      'new_files.*.is_manual' => 'checkbox|nullable',

      'hidden_files' => 'array|nullable',
      'hidden_files.*.title' => 'string|nullable',
      'hidden_files.*.url' => 'string|required',
      'hidden_files.*.position' => 'integer|nullable',
      'hidden_files.*.is_manual' => 'checkbox|nullable',

      'add_bill' => 'boolean|nullable',
      'b_id' => 'int|exists:qb_bills|nullable',
      'b_vendorId' => 'int|nullable',
      'b_status' => 'string|in:due,paid|nullable',
      'b_docNum' => 'string|nullable',
      'b_receivedDate' => 'date|nullable',
      'b_dueDate' => 'date|nullable',
      'b_memo' => 'string|nullable',
      'b_isFloorPlan' => 'bool|nullable',

      'craigslist' => 'array|nullable',
      'craigslist.default_image' => 'array|nullable',
      'craigslist.default_image.new' => 'checkbox|nullable',
      'craigslist.default_image.url' => 'string|nullable',

      'attributes' => 'array|nullable',
      'attributes.*' => 'array',
      'attribute.*.value' => 'string|nullable',

      'features' => 'array|nullable',
      'features.*.value' => 'string',
    ];
}