<?php
namespace Tests\Integration\Http\Controllers\Website\User;

use Tests\database\seeds\Website\WebsiteSeeder;
use Tests\TestCase;

/**
 * Class WebsiteUserControllerTest
 * @package Tests\Integration\Http\Controllers\Website\User
 * @coversDefaultClass \App\Http\Controllers\v1\Website\User\WebsiteUserController
 */
class WebsiteUserControllerTest extends TestCase {
    private $seed;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed = new WebsiteSeeder();
    }

    public function testCreate() {

    }

    public function testLogin() {

    }
}
